class NetworkError(Exception):
	pass

class FinishedError(Exception):
	pass

class InternalError(Exception):
	pass